"""Character-level Markov chain word generator.

Words are generated by chaining overlapping n-grams learned from a training
corpus.  Generation can proceed either left-to-right (*forward*) or
right-to-left (*backward*), which is used by :class:`generators.place_name.PlaceNameGenerator`
to anchor the output to a specific ending pattern.
"""

import random
from collections import defaultdict

from generators.base_generator import BaseGenerator
from helpers.csv_loaders import load_names_with_weights
from generators.word_constraints import WordConstraints, WordExtremes
from generators.helpers import (
    phonetic_match,
    phonetic_search,
    random_choice
)


class MarkovChainWordGenerator(BaseGenerator):
    """Generate novel words by sampling from a character-level Markov chain.

    The chain is built from overlapping n-grams of length *window* with
    *overlap* characters shared between consecutive n-grams.  Sentinel
    characters (``#``) mark word boundaries so the chain learns natural
    start and end sequences.

    Args:
        window: N-gram length (number of characters per token, including
            boundary sentinels).
        overlap: Characters shared between consecutive tokens.  Must be
            less than *window*.
        pattern: Optional phonetic pattern constraining generated words.
            Each pipe-separated sub-pattern must start *or* end with
            ``".+"`` but not both.  Pass ``None`` for unconstrained output.
        forward: If ``True``, generation proceeds left-to-right anchored
            on word beginnings.  If ``False``, right-to-left anchored on
            endings (useful for suffix-constrained place names).
        **constraints: Keyword arguments forwarded to
            :class:`~generators.word_constraints.WordConstraints`
            (e.g. ``max_characters=10``).

    Attributes:
        words: Set of training-corpus words; used to exclude repetitions.
        ngrams: Frequency table of all observed n-grams.
        beginnings: Frequency table of n-grams that start a word.
        endings: Frequency table of n-grams that end a word.
    """

    def __init__(self,
                 window: int,
                 overlap: int,
                 pattern: str | None,
                 forward: bool,
                 **constraints
                 ) -> None:
        super().__init__()
        self.__validate_pattern(pattern)
        self.window = window
        self.overlap = overlap
        self.pattern = pattern
        self.forward = forward
        self.constraints = WordConstraints(**constraints)
        self.words = set()
        self.ngrams = defaultdict(int)
        self.beginnings = defaultdict(int)
        self.endings = defaultdict(int)
        self.paths = []

    def __eq__(self, other: "MarkovChainWordGenerator") -> bool:
        return (
            type(other) is type(self)
            and self.window == other.window
            and self.overlap == other.overlap
            and self.pattern == other.pattern
            and self.forward == other.forward
            and set(self.paths) == set(other.paths) 
            and self.constraints == other.constraints
        )

    def __validate_pattern(self, pattern):
        if pattern is None:
            return
        if any(
            not p.startswith('.+') and not p.endswith('.+')
            for p in pattern.split('|')
        ):
            raise ValueError('Invalid pattern: must either start or end with ".+"')
    
    def train_on_nameset(self, names: list[str]):
        """Build the n-gram tables from an in-memory list of words.

        Words shorter than ``2 * window - overlap`` characters are silently
        skipped because they cannot form a complete n-gram chain.  If a
        *pattern* was provided, only the fixed part of each matching word is
        registered as a beginning or ending anchor.

        After training, :attr:`is_trained` is set to ``True`` and
        :attr:`constraints` is updated with corpus-derived extremes for any
        bounds that were left as ``None``.

        Args:
            names: List of training words.

        Raises:
            ValueError: If no usable beginnings or endings could be
                extracted (e.g. all words are too short, or none match the
                pattern).
        """
        extremes = WordExtremes()
        for raw_word in names:
            word = raw_word.strip()
            if len(word) < 2*self.window - self.overlap:
                continue
            self.words.add(word)
            extremes.update(word)
            word_with_marks = '#' + word + '#'
            for i in range(len(word_with_marks) - self.window + 1):
                ngram = word_with_marks[i:i + self.window]
                self.ngrams[ngram] += 1
            if self.pattern is None:
                self.beginnings[word_with_marks[:self.window]] += 1
                self.endings[word_with_marks[-self.window:]] += 1
            else:
                subpatterns = self.pattern.split('|')
                for subpattern in subpatterns:
                    match = phonetic_match(subpattern, word)
                    if not match:
                        continue
                    match = phonetic_search(subpattern, word)
                    if not match:
                        continue
                    if subpattern.startswith('.+'):
                        self.endings[match+'#'] += 1
                    if subpattern.endswith('.+'):
                        self.beginnings['#'+match] += 1
        if len(self.beginnings) == 0 and len(self.endings) == 0:
            raise ValueError('No available beginnings and endings')
        self.constraints.update_by_extremes(extremes)
        self.is_trained = True

    def train(self):
        """Load corpora from :attr:`paths` and call :meth:`train_on_nameset`.

        Raises:
            ValueError: If all paths are empty or produce no usable words.
        """
        raw_words = []
        for path in self.paths:
            names, _ = load_names_with_weights(path)
            raw_words += names
        if len(raw_words) == 0:
            raise ValueError('Empty training set')
        self.train_on_nameset(raw_words)

    def __generate_one_word_forward(self, subpattern: str | None = None) -> str | None:
        if subpattern is None:
            s = random_choice(self.beginnings)
        else:
            matching_beginnings = {ngram:weight for ngram, weight in self.beginnings.items()
                                if phonetic_match(subpattern.strip('.+'), ngram.strip('#'))}
            if not matching_beginnings:
                return None
            s = random_choice(matching_beginnings)
        if s is None:
            return None
        if s == '#':
            s = random_choice(self.beginnings)

        while (
            s[-1] != '#'
            and self.constraints.match_max(s)
        ):
            possible_next_blocks = {
                ngram:weight for ngram, weight in self.ngrams.items()
                if ngram.startswith(s[-self.overlap:])
            }
            if len(s) == self.constraints.max_characters - (self.window - self.overlap):
                possible_next_blocks_final = {
                    ngram:weight for ngram, weight in possible_next_blocks.items()
                    if ngram[-1] == '#'
                }
                if possible_next_blocks_final:
                    possible_next_blocks = possible_next_blocks_final
            if possible_next_blocks == {}:
                return None
            next_block = random_choice(possible_next_blocks)
            s += next_block[self.overlap:]
        if s[-1] == '#':
            word = s[1:-1]
            return word
        return None

    def __generate_one_word_backward(self, subpattern: str | None = None) -> str | None:
        if subpattern is None:
            s = random_choice(self.endings)
        else:
            matching_endings = {ngram:weight for ngram, weight in self.endings.items()
                                if phonetic_match(subpattern.strip('.+'), ngram.strip('#'))}
            if not matching_endings:
                return None
            s = random_choice(matching_endings)
        if s is None:
            return None
        if s == '#':
            s = random_choice(self.endings)
        while (
            s[0] != '#'
            and self.constraints.match_max(s)
        ):
            possible_next_blocks = {
                ngram:weight for ngram, weight in self.ngrams.items()
                if ngram.endswith(s[:self.overlap])
            }
            if len(s) == self.constraints.max_characters - (self.window - self.overlap):
                possible_next_blocks_final = {
                    ngram:weight for ngram, weight in possible_next_blocks.items()
                    if ngram[0] == '#'
                }
                if possible_next_blocks_final:
                    possible_next_blocks = possible_next_blocks_final
            if possible_next_blocks == {}:
                return None
            next_block = random_choice(possible_next_blocks)
            s = next_block[:self.overlap-1] + s
        if s[0] == '#':
            word = s[1:-1]
            return word
        return None

    def __generate_one_word(self) -> str | None:
        while True:
            if self.pattern is None:
                if self.forward:
                    word = self.__generate_one_word_forward()
                else:
                    word = self.__generate_one_word_backward()
                break
            else:
                subpattern = random.choice(self.pattern.split('|'))
                if subpattern.startswith('.+'):
                    word = self.__generate_one_word_backward(subpattern)
                elif subpattern.endswith('.+'):
                    word = self.__generate_one_word_forward(subpattern)
                if word is None or phonetic_match(subpattern, word):
                    break
        return word
    
    def generate(self,
                 n: int,
                 no_repeat: bool) -> list[str]:
        """Generate up to *n* words by sampling the Markov chain.

        Attempts up to ``10 * n`` trials to collect *n* valid words.  The
        list may be shorter than *n* if the chain cannot produce enough
        distinct valid candidates.

        Args:
            n: Desired number of words.
            no_repeat: If ``True``, exclude training-corpus words and avoid
                duplicates within the returned list.

        Returns:
            Sorted list of generated words.
        """
        if not self.is_trained:
            self.train()
        lst = []
        n_trials = 0
        while len(lst) < n and n_trials < 10 * n:
            n_trials += 1
            word = self.__generate_one_word()
            if word is None:
                continue
            if no_repeat and (word in lst or word in self.words):
                continue
            if not self.constraints.match_max(word):
                continue
            if not self.constraints.match_min(word):
                continue
            lst.append(word)
        return lst
